import {describe,expect,it} from 'vitest';
import {createRider} from '../data/riders';
import {generateOffers} from '../game/career/contracts';
import type {GameState,RiderStats} from '../game/models';
import {riderRankings,teamRankings,u23Rankings} from '../game/world/rankings';
import {createWorld,evolveWorld,recordWorldRace,retirementProbability} from '../game/world/worldSimulation';
import {createCareer,migrateGame,signContract} from '../state/gameStore';

const player=()=>createRider({firstName:'Julian',lastName:'Stehlin',nationality:'France',height:178,weight:66,profile:'grimpeur'});
const flat=(value:number):RiderStats=>({mountain:value,sprint:value,climbing:value,timeTrial:value,pavement:value,endurance:value,explosiveness:value,recovery:value,descending:value,tactics:value,resistance:value,weather:value});
describe('monde et classements V1.6',()=>{
 it('classe d’abord les performances accumulées et non la seule note générale',()=>{const world=createWorld(),low={...world.riders[0],stats:flat(45),seasonPoints:300},high={...world.riders[1],stats:flat(75),seasonPoints:0};world.riders=[low,high];expect(riderRankings(world)[0].id).toBe(low.id)});
 it('produit un classement U23 distinct et correctement renuméroté',()=>{const world=createWorld(),ranking=u23Rankings(world);expect(ranking.every(rider=>rider.age<23)).toBe(true);expect(ranking.map(rider=>rider.position)).toEqual(ranking.map((_,index)=>index+1))});
 it('fait évoluer les points individuels et collectifs après une course',()=>{const world=createWorld(),teamBefore=teamRankings(world)[0].points,race={id:'world-race',name:'Course monde',country:'France',date:'2027-03-01',terrain:'montagne' as const,distance:150,elevation:3000,prestige:50,difficulty:60,status:'completed' as const},updated=recordWorldRace(world,race);expect(updated.riders.some((rider,index)=>rider.seasonPoints>world.riders[index].seasonPoints)).toBe(true);expect(teamRankings(updated)[0].points).toBeGreaterThan(teamBefore)});
 it('est reproductible à données et saison identiques',()=>{const game=createCareer(player()),a=evolveWorld(game.world,game,2028),b=evolveWorld(game.world,game,2028);expect(a).toEqual(b)});
 it('fait évoluer les autres équipes et renouvelle leurs effectifs',()=>{const game=createCareer(player()),next=evolveWorld(game.world,game,2028);expect(next.teams).toHaveLength(game.world.teams.length);expect(next.teams.every(team=>team.roster.length>=8)).toBe(true);expect(next.riders.some(rider=>rider.age!==game.world.riders.find(old=>old.id===rider.id)?.age)).toBe(true)});
 it('génère de jeunes coureurs cohérents avec potentiel et équipe',()=>{const game=createCareer(player()),next=evolveWorld(game.world,game,2028),young=next.riders.filter(rider=>next.youngTalentIds.includes(rider.id));expect(young.length).toBeGreaterThan(0);expect(young.every(rider=>rider.age>=18&&rider.age<=20&&next.teams.some(team=>team.id===rider.teamId))).toBe(true);expect(young.every(rider=>Object.keys(rider.stats).every(key=>rider.potentials[key as keyof RiderStats]>=rider.stats[key as keyof RiderStats]))).toBe(true)});
 it('augmente progressivement la probabilité de retraite et protège les leaders',()=>{const base=createWorld().riders[0],age34={...base,age:34,role:'Équipier' as const},age38={...base,age:38,role:'Équipier' as const},leader={...age38,role:'Leader' as const};expect(retirementProbability(age38)).toBeGreaterThan(retirementProbability(age34));expect(retirementProbability(leader)).toBeLessThan(retirementProbability(age38))});
 it('enregistre des transferts valides entre équipes',()=>{const game=createCareer(player()),next=evolveWorld(game.world,game,2028);expect(next.transfers.every(move=>move.fromTeamId!==move.toTeamId&&next.riders.find(rider=>rider.id===move.riderId)?.teamId===move.toTeamId)).toBe(true)});
 it('réserve les grosses équipes aux profils suffisamment attractifs',()=>{const low=generateOffers(player()),star={...player(),age:20,reputation:25,experience:1200,stats:flat(68)},high=generateOffers(star);expect(Math.max(...low.map(offer=>createWorld().teams.find(team=>team.id===offer.teamId)!.level))).toBeLessThan(4);expect(high.some(offer=>createWorld().teams.find(team=>team.id===offer.teamId)!.level===4)).toBe(true)});
 it('migre une sauvegarde V1.5 sans monde sans perdre la carrière',()=>{let game=createCareer(player());game=signContract(game,game.career.offers[0].id);const legacy={...game,world:undefined} as unknown as GameState,migrated=migrateGame(legacy);expect(migrated.world.teams.length).toBeGreaterThan(0);expect(migrated.rider.id).toBe(game.rider.id);expect(migrated.calendar).toHaveLength(game.calendar.length)});
});
